version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: |
          yarn install --pure-lockfile --no-progress
          yarn build
          yarn test
          yarn coverage
      - save_cache:
          key: dialog-coponents-{{ .Branch }}
          paths:
            - ~/.yarn
            - ~/.yarn-cache
            - ~/.cache/yarn

  deployment:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dialog-coponents-{{ .Branch }}
      - run: |
          yarn
          yarn docs

  npm_publish_prerelease:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: |
          git config --global user.email ${GIT_NAME}
          git config --global user.name ${GIT_EMAIL}
          npm version prerelease --preid=${CIRCLE_BRANCH} --ignore-scripts
          npm publish --tag=${CIRCLE_BRANCH}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deployment:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v\d+(\.\d+)*$/
      - npm_publish_prerelease:
          requires:
            - build
          filters:
            branches:
              ignore: master