version: 2
defaults_run: &defaults_run
  name: run defaults
  command: |
    echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    git config user.email ${GIT_NAME}
    git config user.name ${GIT_EMAIL}
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: |
          yarn install --pure-lockfile --no-progress
          yarn build
          yarn test
          yarn coverage
      - save_cache:
          key: dialog-components-{{ .Branch }}
          paths:
            - ~/.yarn
            - ~/.yarn-cache
            - ~/.cache/yarn

  deployment:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dialog-components-{{ .Branch }}
      - run:
          <<: *defaults_run
      - run: |
          yarn
          yarn docs

  npm_publish_prerelease:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          <<: *defaults_run
      - run: |
          npm version prerelease --preid=${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM} --ignore-scripts
          npm publish --tag=${CIRCLE_BRANCH}

  npm_publish_release:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          <<: *defaults_run
      - run: |
          npm version patch
          npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - npm_publish_release:
          requires:
            - build
          filters:
            branches:
              only: master
      - npm_publish_prerelease:
          requires:
            - build
          filters:
            branches:
              ignore: master