version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: |
          yarn install --pure-lockfile --no-progress
          yarn build
          yarn test
          yarn coverage
      - save_cache:
          key: dialog-coponents-{{ .Branch }}
          paths:
            - ~/.yarn
            - ~/.yarn-cache
            - ~/.cache/yarn
  deployment:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dialog-coponents-{{ .Branch }}
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deployment:
          filters:
            tags:
              - /^v\d+(\.\d+)*$/

# general:
#   branches:
#     ignore:
#       - gh-pages

# machine:
#   # node:
#   #   version: 10
#   environment:
#     GIT_NAME: Circle CI
#     GIT_EMAIL: circle@dlg.im
#     YARN_VERSION: 1.7.0
#     PATH: "${PATH}:${HOME}/.yarn/bin"

# dependencies:
#   pre:
#     # setup git
#     - git config --global user.name "$GIT_NAME"
#     - git config --global user.email "$GIT_EMAIL"
#     # install yarn if it's not already installed
#     - |
#       if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
#         curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
#       fi
#   override:
#     - yarn install --pure-lockfile --no-progress

#   cache_directories:
#     - ~/.yarn
#     - ~/.yarn-cache
#     - ~/.cache/yarn

# test:
#   pre:
#     - yarn build
#   override:
#     - yarn test
#   post:
#     - yarn coverage

# deployment:
#   docs:
#     tag: /^v\d+(\.\d+)*$/
#     owner: dialogs
#     commands:
#       - yarn docs